import { Company, Contact, Employment } from "@/types/contacts";
import { subMonths, subYears } from "date-fns";

export const mockCompanies: Company[] = [
  {
    id: "comp-1",
    name: "TechVision Analytics",
    domain: "techvisionanalytics.com",
    industry: "Technology",
    size: "50-200",
    website: "https://techvisionanalytics.com",
    location: "London, UK",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "comp-2",
    name: "DataStream Solutions",
    domain: "datastream.io",
    industry: "Software",
    size: "200-500",
    website: "https://datastream.io",
    location: "Manchester, UK",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "comp-3",
    name: "CloudFirst Industries",
    domain: "cloudfirst.com",
    industry: "Cloud Services",
    size: "500-1000",
    website: "https://cloudfirst.com",
    location: "Edinburgh, UK",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "comp-4",
    name: "FinanceHub Pro",
    domain: "financehubpro.com",
    industry: "Financial Services",
    size: "100-250",
    website: "https://financehubpro.com",
    location: "Birmingham, UK",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "comp-5",
    name: "RetailMax Group",
    domain: "retailmax.co.uk",
    industry: "Retail",
    size: "1000+",
    website: "https://retailmax.co.uk",
    location: "Leeds, UK",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "comp-6",
    name: "HealthTech Innovations",
    domain: "healthtechinnovations.com",
    industry: "Healthcare",
    size: "50-200",
    website: "https://healthtechinnovations.com",
    location: "Cambridge, UK",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "comp-7",
    name: "EduLearn Platform",
    domain: "edulearn.io",
    industry: "Education",
    size: "200-500",
    website: "https://edulearn.io",
    location: "Oxford, UK",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "comp-8",
    name: "LogisticsPro Ltd",
    domain: "logisticspro.co.uk",
    industry: "Logistics",
    size: "500-1000",
    website: "https://logisticspro.co.uk",
    location: "Bristol, UK",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const mockContacts: Contact[] = [
  {
    id: "contact-1",
    name: "Sarah Mitchell",
    email: "sarah.mitchell@techvisionanalytics.com",
    phone: "+44 20 7946 0958",
    linkedin: "linkedin.com/in/sarahmitchell",
    title: "VP of Sales",
    currentCompanyId: "comp-1",
    currentCompanyName: "TechVision Analytics",
    employmentHistory: [
      {
        id: "emp-1-1",
        companyId: "comp-1",
        companyName: "TechVision Analytics",
        title: "VP of Sales",
        startDate: subYears(new Date(), 2),
        isCurrent: true,
      },
      {
        id: "emp-1-2",
        companyId: "comp-prev-1",
        companyName: "SalesTech Corp",
        title: "Director of Sales",
        startDate: subYears(new Date(), 5),
        endDate: subYears(new Date(), 2),
        isCurrent: false,
      },
    ],
    notes: "Key decision maker, very responsive to data-driven approaches",
    lastActivity: subMonths(new Date(), 1),
    dealCount: 2,
    createdAt: subYears(new Date(), 1),
    updatedAt: new Date(),
  },
  {
    id: "contact-2",
    name: "James Peterson",
    email: "j.peterson@datastream.io",
    phone: "+44 161 123 4567",
    linkedin: "linkedin.com/in/jamespeterson",
    title: "CTO",
    currentCompanyId: "comp-2",
    currentCompanyName: "DataStream Solutions",
    employmentHistory: [
      {
        id: "emp-2-1",
        companyId: "comp-2",
        companyName: "DataStream Solutions",
        title: "CTO",
        startDate: subMonths(new Date(), 8),
        isCurrent: true,
      },
      {
        id: "emp-2-2",
        companyId: "comp-prev-2",
        companyName: "TechCore Ltd",
        title: "VP Engineering",
        startDate: subYears(new Date(), 4),
        endDate: subMonths(new Date(), 8),
        isCurrent: false,
      },
    ],
    notes: "Technical champion, interested in API capabilities",
    lastActivity: subMonths(new Date(), 2),
    dealCount: 1,
    createdAt: subYears(new Date(), 1),
    updatedAt: new Date(),
  },
  {
    id: "contact-3",
    name: "Emma Thompson",
    email: "emma.t@cloudfirst.com",
    phone: "+44 131 555 0199",
    linkedin: "linkedin.com/in/emmathompson",
    title: "Head of Operations",
    currentCompanyId: "comp-3",
    currentCompanyName: "CloudFirst Industries",
    employmentHistory: [
      {
        id: "emp-3-1",
        companyId: "comp-3",
        companyName: "CloudFirst Industries",
        title: "Head of Operations",
        startDate: subYears(new Date(), 3),
        isCurrent: true,
      },
    ],
    notes: "Focus on operational efficiency and ROI",
    lastActivity: new Date(),
    dealCount: 1,
    createdAt: subYears(new Date(), 1),
    updatedAt: new Date(),
  },
  {
    id: "contact-4",
    name: "Michael Chen",
    email: "m.chen@financehubpro.com",
    phone: "+44 121 496 0000",
    linkedin: "linkedin.com/in/michaelchen",
    title: "Chief Revenue Officer",
    currentCompanyId: "comp-4",
    currentCompanyName: "FinanceHub Pro",
    employmentHistory: [
      {
        id: "emp-4-1",
        companyId: "comp-4",
        companyName: "FinanceHub Pro",
        title: "Chief Revenue Officer",
        startDate: subYears(new Date(), 1),
        isCurrent: true,
      },
      {
        id: "emp-4-2",
        companyId: "comp-prev-3",
        companyName: "FinServe Group",
        title: "SVP Sales",
        startDate: subYears(new Date(), 6),
        endDate: subYears(new Date(), 1),
        isCurrent: false,
      },
    ],
    lastActivity: subMonths(new Date(), 1),
    dealCount: 1,
    createdAt: subYears(new Date(), 1),
    updatedAt: new Date(),
  },
  {
    id: "contact-5",
    name: "Laura Davies",
    email: "laura.davies@retailmax.co.uk",
    phone: "+44 113 234 5678",
    linkedin: "linkedin.com/in/lauradavies",
    title: "Director of Technology",
    currentCompanyId: "comp-5",
    currentCompanyName: "RetailMax Group",
    employmentHistory: [
      {
        id: "emp-5-1",
        companyId: "comp-5",
        companyName: "RetailMax Group",
        title: "Director of Technology",
        startDate: subYears(new Date(), 4),
        isCurrent: true,
      },
    ],
    notes: "Large enterprise, long sales cycle expected",
    lastActivity: subMonths(new Date(), 3),
    dealCount: 1,
    createdAt: subYears(new Date(), 1),
    updatedAt: new Date(),
  },
  {
    id: "contact-6",
    name: "Robert Williams",
    email: "r.williams@healthtechinnovations.com",
    phone: "+44 1223 123456",
    linkedin: "linkedin.com/in/robertwilliams",
    title: "CEO",
    currentCompanyId: "comp-6",
    currentCompanyName: "HealthTech Innovations",
    employmentHistory: [
      {
        id: "emp-6-1",
        companyId: "comp-6",
        companyName: "HealthTech Innovations",
        title: "CEO",
        startDate: subYears(new Date(), 5),
        isCurrent: true,
      },
    ],
    notes: "Founder, very hands-on in evaluation process",
    lastActivity: subMonths(new Date(), 2),
    dealCount: 1,
    createdAt: subYears(new Date(), 1),
    updatedAt: new Date(),
  },
  {
    id: "contact-7",
    name: "Sophie Anderson",
    email: "sophie.a@edulearn.io",
    phone: "+44 1865 555 0123",
    linkedin: "linkedin.com/in/sophieanderson",
    title: "VP Product",
    currentCompanyId: "comp-7",
    currentCompanyName: "EduLearn Platform",
    employmentHistory: [
      {
        id: "emp-7-1",
        companyId: "comp-7",
        companyName: "EduLearn Platform",
        title: "VP Product",
        startDate: subMonths(new Date(), 10),
        isCurrent: true,
      },
      {
        id: "emp-7-2",
        companyId: "comp-prev-4",
        companyName: "EdTech Solutions",
        title: "Senior Product Manager",
        startDate: subYears(new Date(), 3),
        endDate: subMonths(new Date(), 10),
        isCurrent: false,
      },
    ],
    lastActivity: subMonths(new Date(), 1),
    dealCount: 1,
    createdAt: subMonths(new Date(), 11),
    updatedAt: new Date(),
  },
  {
    id: "contact-8",
    name: "David Martinez",
    email: "d.martinez@logisticspro.co.uk",
    phone: "+44 117 926 0000",
    linkedin: "linkedin.com/in/davidmartinez",
    title: "Operations Manager",
    currentCompanyId: "comp-8",
    currentCompanyName: "LogisticsPro Ltd",
    employmentHistory: [
      {
        id: "emp-8-1",
        companyId: "comp-8",
        companyName: "LogisticsPro Ltd",
        title: "Operations Manager",
        startDate: subYears(new Date(), 2),
        isCurrent: true,
      },
    ],
    lastActivity: subMonths(new Date(), 4),
    dealCount: 1,
    createdAt: subYears(new Date(), 1),
    updatedAt: new Date(),
  },
  {
    id: "contact-9",
    name: "Rachel Green",
    email: "rachel.green@techvisionanalytics.com",
    phone: "+44 20 7946 0959",
    linkedin: "linkedin.com/in/rachelgreen",
    title: "Marketing Director",
    currentCompanyId: "comp-1",
    currentCompanyName: "TechVision Analytics",
    employmentHistory: [
      {
        id: "emp-9-1",
        companyId: "comp-1",
        companyName: "TechVision Analytics",
        title: "Marketing Director",
        startDate: subYears(new Date(), 1),
        isCurrent: true,
      },
    ],
    notes: "Influencer in buying decision, focuses on brand alignment",
    lastActivity: subMonths(new Date(), 1),
    dealCount: 1,
    createdAt: subYears(new Date(), 1),
    updatedAt: new Date(),
  },
  {
    id: "contact-10",
    name: "Oliver Johnson",
    email: "oliver.j@datastream.io",
    phone: "+44 161 123 4568",
    linkedin: "linkedin.com/in/oliverjohnson",
    title: "CFO",
    currentCompanyId: "comp-2",
    currentCompanyName: "DataStream Solutions",
    employmentHistory: [
      {
        id: "emp-10-1",
        companyId: "comp-2",
        companyName: "DataStream Solutions",
        title: "CFO",
        startDate: subYears(new Date(), 3),
        isCurrent: true,
      },
    ],
    notes: "Budget holder, requires detailed ROI analysis",
    lastActivity: subMonths(new Date(), 2),
    dealCount: 1,
    createdAt: subYears(new Date(), 1),
    updatedAt: new Date(),
  },
];
