trigger:
  branches:
    include:
      - Dev
  paths:
    exclude:
      - "*"
variables:
  - group: frontend-secrets
  - name: IMAGE_NAME
    value: PLN1000013_MERN_Development
pool:
  vmImage: ubuntu-latest
steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "22.x"
    displayName: "Install Node.js"
  - script: npm install --force
    displayName: "Install dependencies"
  - script: |
      echo "VITE_PASSWORD_SALT=$(VITE_PASSWORD_SALT)" >> .env
      echo "VITE_JWT_SECRET=$(VITE_JWT_SECRET)" >> .env
      echo "VITE_HUBSPOT_CLIENT_ID=$(VITE_HUBSPOT_CLIENT_ID)" >> .env
      echo "VITE_HUBSPOT_CLIENT_SECRET=$(VITE_HUBSPOT_CLIENT_SECRET)" >> .env
      echo "VITE_HUBSPOT_REDIRECT_URI=$(VITE_HUBSPOT_REDIRECT_URI)" >> .env
      echo "VITE_POSTHOG_KEY=$(VITE_POSTHOG_KEY)" >> .env
      echo "VITE_POSTHOG_HOST=$(VITE_POSTHOG_HOST)" >> .env
      echo "VITE_POSTHOG_ANALYTICS=$(VITE_POSTHOG_ANALYTICS)" >> .env
      echo "VITE_SUPABASE_URL=$(VITE_SUPABASE_URL)" >> .env
      echo "VITE_SUPABASE_ANON_KEY=$(VITE_SUPABASE_ANON_KEY)" >> .env
      echo "VITE_API_BASE_URL=$(VITE_API_BASE_URL)" >> .env
    displayName: "Create .env file"
  - script: npm run build
    displayName: "Build frontend"
  - script: |
      cd dist
      sudo tar -czvf pln1000013.tar.gz *
      mv pln1000013.tar.gz ..
    displayName: "Create tar.gz Archive of Build Files"
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(System.DefaultWorkingDirectory)/pln1000013.tar.gz
      artifactName: react-build
    displayName: "Publish Build Artifact"
